name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo
  XP12VWS_VERSION: 1.0.0

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest          

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v4

    - name: "Windows: Configure environment"
      if: runner.os == 'Windows'
      shell: bash
      run: |
        # Select MinGW toolchain instead of the default MSVC.
        echo "CMAKE_GENERATOR=MinGW Makefiles" >> $GITHUB_ENV

    - name: "Linux: Install dependency libraries"
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends freeglut3-dev libudev-dev libopenal-dev

    - name: Configure CMake
      working-directory: ${{github.workspace}}/src
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ${{github.workspace}}/src
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
      
    - uses: actions/upload-artifact@v4
      with:
        name: binaries-${{matrix.os}}
        path: ${{github.workspace}}/build/*.xpl
        if-no-files-found: error

  package:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/upload-artifact/merge@v4
        with:
          name: binaries
          pattern: binaries-*

      - uses: actions/download-artifact@v4
        with:
          name: binaries
          path: VR_Window_Sample/64

      - uses: actions/upload-artifact@v4
        with:
          name: VR_Window_Sample_v${{env.XP12VWS_VERSION}}
          path: |
            ${{github.workspace}}/VR_Window_Sample*
          if-no-files-found: error
